# Numpy 
The core library for scientific computing in Python. 
It provides a high-performance multidimensional array object, and tools for working with these arrays.

This script was modified from the original at (https://cs231n.github.io/python-numpy-tutorial/)

In [2]:
import numpy as np 

In [4]:
a = np.array([1, 2, 3])   # Create a rank 1 array
type(a) 

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
print(a[0], a[1], a[2])

1 2 3


In [7]:
a[0] = 5
a

array([5, 2, 3])

In [12]:
c = np.array([12, 13, 14])
c

array([12, 13, 14])

In [11]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

## Array Creation

In [15]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)             

[[0. 0.]
 [0. 0.]]


In [16]:
b = np.ones((1,2))    # Create an array of all ones
print(b)             

[[1. 1.]]


In [17]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               

[[7 7]
 [7 7]]


In [18]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)             

[[1. 0.]
 [0. 1.]]


In [39]:
# e = np.random.normal(10, 10, size = (2, 2))  # Create an array filled with random values
e = np.random.normal(3, 2.5, size=(2, 4))
print(e)

[[ 4.55790302  1.39430901  6.93659912 -1.36904429]
 [ 2.80355599  2.29750127  1.64571183  2.95841487]]


In [52]:
help(np.random.exponential)

Help on built-in function exponential:

exponential(...) method of numpy.random.mtrand.RandomState instance
    exponential(scale=1.0, size=None)
    
    Draw samples from an exponential distribution.
    
    Its probability density function is
    
    .. math:: f(x; \frac{1}{\beta}) = \frac{1}{\beta} \exp(-\frac{x}{\beta}),
    
    for ``x > 0`` and 0 elsewhere. :math:`\beta` is the scale parameter,
    which is the inverse of the rate parameter :math:`\lambda = 1/\beta`.
    The rate parameter is an alternative, widely used parameterization
    of the exponential distribution [3]_.
    
    The exponential distribution is a continuous analogue of the
    geometric distribution.  It describes many common situations, such as
    the size of raindrops measured over many rainstorms [1]_, or the time
    between page requests to Wikipedia [2]_.
    
    .. note::
        New code should use the ``exponential`` method of a ``default_rng()``
        instance instead; see `random-quick-s

In [62]:
np.linspace(1, 24, 24)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [76]:
np.arange(0, 24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [80]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [85]:
x = np.arange(0, 24)
a = np.array(x)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
type(x)
x.shape = (2, 12)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [89]:
a = np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [84]:
a.shape = (2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [82]:
a.shape = (2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Array Indexing

In [90]:
## Array indexing
#Numpy offers several ways to index into arrays.
# Slicing: Similar to Python lists, numpy arrays can be sliced. 
# Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3] # :2 give index 0 and 1
                # 1:3 gives index 1 and 2 out of (0, 1, 2, 3)
b

array([[2, 3],
       [6, 7]])

In [93]:
c = a[1:3, 2:4]
c

array([[ 7,  8],
       [11, 12]])

In [94]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


This phenomenon above is VERY different than what we are used to in R.

This tutorial will be continuted in the day6 notebook...