# Numpy 
The core library for scientific computing in Python. 
It provides a high-performance multidimensional array object, and tools for working with these arrays.

This script was modified from the original at (https://cs231n.github.io/python-numpy-tutorial/)

In [2]:
import numpy as np 

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
type(a) 

numpy.ndarray

In [4]:
a.shape

(3,)

In [5]:
print(a[0], a[1], a[2])

1 2 3


In [6]:
a[0] = 5
a

array([5, 2, 3])

In [7]:
c = np.array([12, 13, 14])
c

array([12, 13, 14])

In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

## Array Creation

In [11]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)             

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)             

[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               

[[7 7]
 [7 7]]


In [14]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)             

[[1. 0.]
 [0. 1.]]


In [15]:
# e = np.random.normal(10, 10, size = (2, 2))  # Create an array filled with random values
e = np.random.normal(3, 2.5, size=(2, 4))
print(e)

[[ 5.97148533 -0.39218485  6.17155593  2.09749858]
 [ 2.98237745  6.27380425  1.93655963  1.87524006]]


In [ ]:
help(np.random.exponential)

In [16]:
np.linspace(1, 24, 5) # last arguement is the length of sequence (defaults to 50)

array([ 1.  ,  6.75, 12.5 , 18.25, 24.  ])

In [17]:
np.arange(0, 24, 2) # last arg is the step-size (defaults to 1)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [ ]:
help(np.array)

In [ ]:
x = np.arange(0, 24)
type(x)

In [ ]:
a = np.array(x)
a
type(a)

In [ ]:
x.shape = (2, 12)
print(x)
type(x)

In [ ]:
a = np.array(range(24))
a

In [ ]:
a.shape = (2, 12)
a

In [ ]:
a.shape = (2, 3, 4)
a

## Array Indexing

In [35]:
## Array indexing
#Numpy offers several ways to index into arrays.
# Slicing: Similar to Python lists, numpy arrays can be sliced. 
# Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3] # :2 give index 0 and 1
                # 1:3 gives index 1 and 2 out of (0, 1, 2, 3)
b

array([[2, 3],
       [6, 7]])

In [24]:
# Floor function
arr = [0.23, 0.09, 1.2, 1.24, 9.99]    
r_arr = np.floor(arr)  
print(r_arr)

[0. 0. 1. 1. 9.]


In [25]:
c = a[1:3, 2:4]
c

array([[ 7,  8],
       [11, 12]])

In [27]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
print(a)

77
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [38]:
c = np.matmul(e, b)
c

array([[2., 3.],
       [6., 7.]])

In [41]:
c[0, 0] = 77
c
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

This phenomenon above is VERY different than what we are used to in R.

This tutorial will be continuted in the day6 notebook...